name: Build Win64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        continue-on-error: true # Если установка упадет, но .NET уже есть в системе — идем дальше
        with:
          dotnet-version: '9.0.x' # Укажите вашу версию .NET
          cache: true # Включает автоматическое кэширование зависимостей
          cache-dependency-path: '*.csproj' # Или '**/packages.lock.json'

      - name: Publish Application
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o "${{ github.workspace }}/publish"

      - name: Zip Artifact
        shell: pwsh
        run: |
          # Проверяем, есть ли файлы, прежде чем архивировать (для отладки)
          if (Test-Path "${{ github.workspace }}/publish/*") {
              Compress-Archive -Path "${{ github.workspace }}/publish/*" -DestinationPath "Windows-x64-ReserK.zip" -Force
          } else {
              Write-Error "Папка publish пуста! Сборка не удалась."
              exit 1
          }

      - name: Upload Artifact to Actions
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-ReserK
          path: Windows-x64-ReserK.zip
          retention-days: 1
