name: Release Win64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Запуск релиза при создании тега (напр. v1.0.0)
  pull_request:
    branches:
      - main # Проверка сборки при PR
      - master

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows-x64-ReserK # Имя должно совпадать с тем, что в upload-artifact
          
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # После download-artifact файл будет лежать в текущей папке
          files: Windows-x64-ReserK.zip
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true # Автоматически создаст описание из списка коммитов
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
